package hoon.schooldb.models;

public enum Major {
    ART,
    ART_EDUCATION,
    ART_HISTORY,
    BIOMEDICAL_ENGR,
    CHEMICAL_ENGR,
    BIOCHEMISTRY,
    CHILDHOOD_EDUCATION,
    CIVIL_ENGR,
    MATHMATICS,
    ECONOMICS,
    BUSINESS,
    ENGLISH,
    HISTORY,
    PHILOSOPY,
    PSYCHOLOGY,
    SOCIOLOGY,
    COMPUTER_ENGR,
    COMPUTER_SCIENCE,
    ELECTRICAL_ENGR,
    MECHANICAL_ENGR,
    BUSINESS_ADMIN,
    ACCOUNTING,
    MUSIC,
    PHYSICS,
    BIOLOGY
}
